In [1]:
import pandas as pd
import json
import requests

# coba input

In [2]:
lat_ori = input('Masukkan lat asal:')
long_ori = input('Masukkan long asal:')
radius = input('Masukkan radius(dalam meter):')
types_user = input('Masukkan types:')
keyword_user = input('Masukkan keyword:')
#-6.2097
#106.90166

Masukkan lat asal:-6.2097
Masukkan long asal:106.90166
Masukkan radius(dalam meter):1000
Masukkan types:atm
Masukkan keyword:mandiri

In [3]:
data_cust={}
latitude, longitude, name, place_id, types_places, vicinity = [],[],[],[],[],[]

apik = 'AIzaSyCi3bprtv8GbZUNpU4rE2eQ8oguxfDkRjg'
urls = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?location={},{}&radius={}&key={}&type={}&keyword={}'.format(lat_ori,long_ori,radius,apik,types_user,keyword_user)
r = requests.get(urls)
data_cust[types_user] = r.json()
for number in range(len(data_cust[types_user]['results'])):
    latitude.append(data_cust[types_user]['results'][number]['geometry']['location']['lat'])
    longitude.append(data_cust[types_user]['results'][number]['geometry']['location']['lng'])
    name.append(data_cust[types_user]['results'][number]['name'])
    place_id.append(data_cust[types_user]['results'][number]['place_id'])
    types_places.append(data_cust[types_user]['results'][number]['types'][0])
    vicinity.append(data_cust[types_user]['results'][number]['vicinity'])

In [4]:
datacustype = pd.DataFrame({'customer_name':name,'customer_address':vicinity,'customer_type':types_places,'place_id':place_id,
                            'keyword':keyword_user,'radius':radius,'latitude_origin':lat_ori,'longitude_origin':long_ori,'latitude_destination':latitude,
                            'longitude_destination':longitude})
datacustype

,customer_name,customer_address,customer_type,place_id,keyword,radius,latitude_origin,longitude_origin,latitude_destination,longitude_destination
0,ATM Mandiri,"Jl. Bekasi Timur Raya No.48c, RT.13/RW.2, Jati...",atm,ChIJU7kJa6_0aS4ReDXWEVlKU_U,mandiri,1000,-6.2097,106.90166,-6.208364,106.901700
1,Mandiri ATM Citra Klender,"Jl. I Gusti Ngurah Rai, RT.4/RW.6, Klender, Ko...",bank,ChIJZdR0VVXzaS4RtsxK_SQ_5WA,mandiri,1000,-6.2097,106.90166,-6.213986,106.903752
2,Mandiri ATM MITSUBISHI Pulo Gadung,"Jl. Raya Bekasi Pulogadung, RT.2/RW.14, Cipina...",bank,ChIJZ04RRKH0aS4R_intKrJbNXM,mandiri,1000,-6.2097,106.90166,-6.210821,106.893506
3,ATM Mandiri,"Toserba Berkah, Jl. Gurame No.31, RT.4/RW.6, J...",atm,ChIJq3xR3bv0aS4RxuJJ79yN3AE,mandiri,1000,-6.2097,106.90166,-6.200196,106.896083
4,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,"Jalan Pahlawan Revolusi No.12 RT.9/RW.4, RT.11...",bank,ChIJyUcV9lnzaS4R5feGiOKucYk,mandiri,1000,-6.2097,106.90166,-6.217153,106.899841
5,Mandiri Micro Business Unit Jakarta Mall Klender,Komplek Ruko Blok B1 No.6 Jl. I Gusti Ngurah R...,bank,ChIJ-frTp6r0aS4ROzw41QWz3WE,mandiri,1000,-6.2097,106.90166,-6.213992,106.903753
6,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No.5a, RT.12/RW.7, Rawamangun, ...",atm,ChIJ6Ugu3L30aS4RNE-0s3lxyXg,mandiri,1000,-6.2097,106.90166,-6.200591,106.890660
7,ATM BTN,"Jl. Pahlawan Revolusi, RT.11/RW.5, Klender, Ko...",atm,ChIJG3jbLVjzaS4RzCcRRA3jPmk,mandiri,1000,-6.2097,106.90166,-6.218380,106.899969
8,ATM CIMB Niaga,"SPBU Pertamina ATM Centre, Jalan Bekasi Timur ...",atm,ChIJiZsg1af0aS4Ro11lGyH9UcM,mandiri,1000,-6.2097,106.90166,-6.212319,106.900264
9,ATM CIMB Niaga,"Jl. Raya Bekasi No.KM 17, RT.7/RW.3, Jatinegar...",atm,ChIJVX_Xo7H0aS4R7zCX77Rv004,mandiri,1000,-6.2097,106.90166,-6.202227,106.904644
10,Mandiri ATM Alfamart Dermaga,"JL Dermaga Raya, No. 4 RT. 003 RW. 017, Klende...",atm,ChIJsyZPE1PzaS4RbWvoHjwXkN4,mandiri,1000,-6.2097,106.90166,-6.220890,106.910342
11,Bank Mandiri Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No. 4, Rawamangun, Jati, Puloga...",bank,ChIJ-2eYub30aS4R_U7u5oQpTus,mandiri,1000,-6.2097,106.90166,-6.201320,106.890710
12,Atm Bank Dki,"Pasar Jaya Klender SS, Jl. Bekasi Timur Raya N...",atm,ChIJY7IpZ6j0aS4RMnCwUZJ42iE,mandiri,1000,-6.2097,106.90166,-6.212552,106.901747

# phone numb

In [5]:
data_number = {}
for number in datacustype['place_id'].values:
    apik = 'AIzaSyCi3bprtv8GbZUNpU4rE2eQ8oguxfDkRjg'
    urls = 'https://maps.googleapis.com/maps/api/place/details/json?place_id={}&fields=name,rating,formatted_phone_number&key={}'.format(number,apik)
    r = requests.get(urls)
    data_number[number] = r.json()

In [6]:
data_number

{'ChIJU7kJa6_0aS4ReDXWEVlKU_U': {'html_attributions': [],
  'result': {'name': 'ATM Mandiri'},
  'status': 'OK'},
 'ChIJZdR0VVXzaS4RtsxK_SQ_5WA': {'html_attributions': [],
  'result': {'formatted_phone_number': '(021) 86612125',
   'name': 'Mandiri ATM Citra Klender',
   'rating': 3.5},
  'status': 'OK'},
 'ChIJZ04RRKH0aS4R_intKrJbNXM': {'html_attributions': [],
  'result': {'formatted_phone_number': '(021) 52997777',
   'name': 'Mandiri ATM MITSUBISHI Pulo Gadung'},
  'status': 'OK'},
 'ChIJq3xR3bv0aS4RxuJJ79yN3AE': {'html_attributions': [],
  'result': {'name': 'ATM Mandiri', 'rating': 5},
  'status': 'OK'},
 'ChIJyUcV9lnzaS4R5feGiOKucYk': {'html_attributions': [],
  'result': {'formatted_phone_number': '(021) 8625120',
   'name': 'Bank Mandiri - Branch Jakarta Pahlawan Revolusi',
   'rating': 4},
  'status': 'OK'},
 'ChIJ-frTp6r0aS4ROzw41QWz3WE': {'html_attributions': [],
  'result': {'formatted_phone_number': '(021) 86612125',
   'name': 'Mandiri Micro Business Unit Jakarta Mall Klender',
   'rating': 4},
  'status': 'OK'},
 'ChIJ6Ugu3L30aS4RNE-0s3lxyXg': {'html_attributions': [],
  'result': {'formatted_phone_number': '(021) 52997777',
   'name': 'Mandiri ATM KCP Jakarta Rawamangun Pegambiran',
   'rating': 3.3},
  'status': 'OK'},
 'ChIJG3jbLVjzaS4RzCcRRA3jPmk': {'html_attributions': [],
  'result': {'name': 'ATM BTN', 'rating': 5},
  'status': 'OK'},
 'ChIJiZsg1af0aS4Ro11lGyH9UcM': {'html_attributions': [],
  'result': {'name': 'ATM CIMB Niaga', 'rating': 5},
  'status': 'OK'},
 'ChIJVX_Xo7H0aS4R7zCX77Rv004': {'html_attributions': [],
  'result': {'name': 'ATM CIMB Niaga'},
  'status': 'OK'},
 'ChIJsyZPE1PzaS4RbWvoHjwXkN4': {'html_attributions': [],
  'result': {'name': 'Mandiri ATM Alfamart Dermaga', 'rating': 5},
  'status': 'OK'},
 'ChIJ-2eYub30aS4R_U7u5oQpTus': {'html_attributions': [],
  'result': {'formatted_phone_number': '(021) 4892878',
   'name': 'Bank Mandiri Jakarta Rawamangun Pegambiran',
   'rating': 4.8},
  'status': 'OK'},
 'ChIJY7IpZ6j0aS4RMnCwUZJ42iE': {'html_attributions': [],
  'result': {'name': 'Atm Bank Dki', 'rating': 1},
  'status': 'OK'}}

In [7]:
datanumb = pd.DataFrame.from_dict(data_number).T.reset_index()
datanumb.columns = ['place_id','html_attributions','result','status']
datanumb

,place_id,html_attributions,result,status
0,ChIJU7kJa6_0aS4ReDXWEVlKU_U,[],{'name': 'ATM Mandiri'},OK
1,ChIJZdR0VVXzaS4RtsxK_SQ_5WA,[],"{'formatted_phone_number': '(021) 86612125', '...",OK
2,ChIJZ04RRKH0aS4R_intKrJbNXM,[],"{'formatted_phone_number': '(021) 52997777', '...",OK
3,ChIJq3xR3bv0aS4RxuJJ79yN3AE,[],"{'name': 'ATM Mandiri', 'rating': 5}",OK
4,ChIJyUcV9lnzaS4R5feGiOKucYk,[],"{'formatted_phone_number': '(021) 8625120', 'n...",OK
5,ChIJ-frTp6r0aS4ROzw41QWz3WE,[],"{'formatted_phone_number': '(021) 86612125', '...",OK
6,ChIJ6Ugu3L30aS4RNE-0s3lxyXg,[],"{'formatted_phone_number': '(021) 52997777', '...",OK
7,ChIJG3jbLVjzaS4RzCcRRA3jPmk,[],"{'name': 'ATM BTN', 'rating': 5}",OK
8,ChIJiZsg1af0aS4Ro11lGyH9UcM,[],"{'name': 'ATM CIMB Niaga', 'rating': 5}",OK
9,ChIJVX_Xo7H0aS4R7zCX77Rv004,[],{'name': 'ATM CIMB Niaga'},OK
10,ChIJsyZPE1PzaS4RbWvoHjwXkN4,[],"{'name': 'Mandiri ATM Alfamart Dermaga', 'rati...",OK
11,ChIJ-2eYub30aS4R_U7u5oQpTus,[],"{'formatted_phone_number': '(021) 4892878', 'n...",OK
12,ChIJY7IpZ6j0aS4RMnCwUZJ42iE,[],"{'name': 'Atm Bank Dki', 'rating': 1}",OK

In [8]:
name= []
phone=[]

for number in range(len(datanumb)):
    if datanumb['status'][number] == 'NOT_FOUND':
        name.append('Unknown')
        phone.append(0)
    else:
        name.append(datanumb['result'][number]['name'])
        if 'formatted_phone_number' in (datanumb['result'][number].keys()):
            phone.append(datanumb['result'][number]['formatted_phone_number'])
        else:
            phone.append(0)

In [9]:
datanumb2 = pd.DataFrame({'customer_name':name,'phone_number':phone})
datanumb2['place_id'] = datanumb['place_id']
datanumb2

,customer_name,phone_number,place_id
0,ATM Mandiri,0,ChIJU7kJa6_0aS4ReDXWEVlKU_U
1,Mandiri ATM Citra Klender,(021) 86612125,ChIJZdR0VVXzaS4RtsxK_SQ_5WA
2,Mandiri ATM MITSUBISHI Pulo Gadung,(021) 52997777,ChIJZ04RRKH0aS4R_intKrJbNXM
3,ATM Mandiri,0,ChIJq3xR3bv0aS4RxuJJ79yN3AE
4,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,(021) 8625120,ChIJyUcV9lnzaS4R5feGiOKucYk
5,Mandiri Micro Business Unit Jakarta Mall Klender,(021) 86612125,ChIJ-frTp6r0aS4ROzw41QWz3WE
6,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,(021) 52997777,ChIJ6Ugu3L30aS4RNE-0s3lxyXg
7,ATM BTN,0,ChIJG3jbLVjzaS4RzCcRRA3jPmk
8,ATM CIMB Niaga,0,ChIJiZsg1af0aS4Ro11lGyH9UcM
9,ATM CIMB Niaga,0,ChIJVX_Xo7H0aS4R7zCX77Rv004
10,Mandiri ATM Alfamart Dermaga,0,ChIJsyZPE1PzaS4RbWvoHjwXkN4
11,Bank Mandiri Jakarta Rawamangun Pegambiran,(021) 4892878,ChIJ-2eYub30aS4R_U7u5oQpTus
12,Atm Bank Dki,0,ChIJY7IpZ6j0aS4RMnCwUZJ42iE

# merge

In [10]:
datamerge=datacustype.merge(datanumb2, how='left', on='place_id')
#datagab3=datab2.join(datanumb2.set_index('place_id'),on='place_id')
datamerge

,customer_name_x,customer_address,customer_type,place_id,keyword,radius,latitude_origin,longitude_origin,latitude_destination,longitude_destination,customer_name_y,phone_number
0,ATM Mandiri,"Jl. Bekasi Timur Raya No.48c, RT.13/RW.2, Jati...",atm,ChIJU7kJa6_0aS4ReDXWEVlKU_U,mandiri,1000,-6.2097,106.90166,-6.208364,106.901700,ATM Mandiri,0
1,Mandiri ATM Citra Klender,"Jl. I Gusti Ngurah Rai, RT.4/RW.6, Klender, Ko...",bank,ChIJZdR0VVXzaS4RtsxK_SQ_5WA,mandiri,1000,-6.2097,106.90166,-6.213986,106.903752,Mandiri ATM Citra Klender,(021) 86612125
2,Mandiri ATM MITSUBISHI Pulo Gadung,"Jl. Raya Bekasi Pulogadung, RT.2/RW.14, Cipina...",bank,ChIJZ04RRKH0aS4R_intKrJbNXM,mandiri,1000,-6.2097,106.90166,-6.210821,106.893506,Mandiri ATM MITSUBISHI Pulo Gadung,(021) 52997777
3,ATM Mandiri,"Toserba Berkah, Jl. Gurame No.31, RT.4/RW.6, J...",atm,ChIJq3xR3bv0aS4RxuJJ79yN3AE,mandiri,1000,-6.2097,106.90166,-6.200196,106.896083,ATM Mandiri,0
4,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,"Jalan Pahlawan Revolusi No.12 RT.9/RW.4, RT.11...",bank,ChIJyUcV9lnzaS4R5feGiOKucYk,mandiri,1000,-6.2097,106.90166,-6.217153,106.899841,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,(021) 8625120
5,Mandiri Micro Business Unit Jakarta Mall Klender,Komplek Ruko Blok B1 No.6 Jl. I Gusti Ngurah R...,bank,ChIJ-frTp6r0aS4ROzw41QWz3WE,mandiri,1000,-6.2097,106.90166,-6.213992,106.903753,Mandiri Micro Business Unit Jakarta Mall Klender,(021) 86612125
6,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No.5a, RT.12/RW.7, Rawamangun, ...",atm,ChIJ6Ugu3L30aS4RNE-0s3lxyXg,mandiri,1000,-6.2097,106.90166,-6.200591,106.890660,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,(021) 52997777
7,ATM BTN,"Jl. Pahlawan Revolusi, RT.11/RW.5, Klender, Ko...",atm,ChIJG3jbLVjzaS4RzCcRRA3jPmk,mandiri,1000,-6.2097,106.90166,-6.218380,106.899969,ATM BTN,0
8,ATM CIMB Niaga,"SPBU Pertamina ATM Centre, Jalan Bekasi Timur ...",atm,ChIJiZsg1af0aS4Ro11lGyH9UcM,mandiri,1000,-6.2097,106.90166,-6.212319,106.900264,ATM CIMB Niaga,0
9,ATM CIMB Niaga,"Jl. Raya Bekasi No.KM 17, RT.7/RW.3, Jatinegar...",atm,ChIJVX_Xo7H0aS4R7zCX77Rv004,mandiri,1000,-6.2097,106.90166,-6.202227,106.904644,ATM CIMB Niaga,0
10,Mandiri ATM Alfamart Dermaga,"JL Dermaga Raya, No. 4 RT. 003 RW. 017, Klende...",atm,ChIJsyZPE1PzaS4RbWvoHjwXkN4,mandiri,1000,-6.2097,106.90166,-6.220890,106.910342,Mandiri ATM Alfamart Dermaga,0
11,Bank Mandiri Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No. 4, Rawamangun, Jati, Puloga...",bank,ChIJ-2eYub30aS4R_U7u5oQpTus,mandiri,1000,-6.2097,106.90166,-6.201320,106.890710,Bank Mandiri Jakarta Rawamangun Pegambiran,(021) 4892878
12,Atm Bank Dki,"Pasar Jaya Klender SS, Jl. Bekasi Timur Raya N...",atm,ChIJY7IpZ6j0aS4RMnCwUZJ42iE,mandiri,1000,-6.2097,106.90166,-6.212552,106.901747,Atm Bank Dki,0

# dummy

In [11]:
datadummy=datamerge.copy()
datadummy

,customer_name_x,customer_address,customer_type,place_id,keyword,radius,latitude_origin,longitude_origin,latitude_destination,longitude_destination,customer_name_y,phone_number
0,ATM Mandiri,"Jl. Bekasi Timur Raya No.48c, RT.13/RW.2, Jati...",atm,ChIJU7kJa6_0aS4ReDXWEVlKU_U,mandiri,1000,-6.2097,106.90166,-6.208364,106.901700,ATM Mandiri,0
1,Mandiri ATM Citra Klender,"Jl. I Gusti Ngurah Rai, RT.4/RW.6, Klender, Ko...",bank,ChIJZdR0VVXzaS4RtsxK_SQ_5WA,mandiri,1000,-6.2097,106.90166,-6.213986,106.903752,Mandiri ATM Citra Klender,(021) 86612125
2,Mandiri ATM MITSUBISHI Pulo Gadung,"Jl. Raya Bekasi Pulogadung, RT.2/RW.14, Cipina...",bank,ChIJZ04RRKH0aS4R_intKrJbNXM,mandiri,1000,-6.2097,106.90166,-6.210821,106.893506,Mandiri ATM MITSUBISHI Pulo Gadung,(021) 52997777
3,ATM Mandiri,"Toserba Berkah, Jl. Gurame No.31, RT.4/RW.6, J...",atm,ChIJq3xR3bv0aS4RxuJJ79yN3AE,mandiri,1000,-6.2097,106.90166,-6.200196,106.896083,ATM Mandiri,0
4,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,"Jalan Pahlawan Revolusi No.12 RT.9/RW.4, RT.11...",bank,ChIJyUcV9lnzaS4R5feGiOKucYk,mandiri,1000,-6.2097,106.90166,-6.217153,106.899841,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,(021) 8625120
5,Mandiri Micro Business Unit Jakarta Mall Klender,Komplek Ruko Blok B1 No.6 Jl. I Gusti Ngurah R...,bank,ChIJ-frTp6r0aS4ROzw41QWz3WE,mandiri,1000,-6.2097,106.90166,-6.213992,106.903753,Mandiri Micro Business Unit Jakarta Mall Klender,(021) 86612125
6,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No.5a, RT.12/RW.7, Rawamangun, ...",atm,ChIJ6Ugu3L30aS4RNE-0s3lxyXg,mandiri,1000,-6.2097,106.90166,-6.200591,106.890660,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,(021) 52997777
7,ATM BTN,"Jl. Pahlawan Revolusi, RT.11/RW.5, Klender, Ko...",atm,ChIJG3jbLVjzaS4RzCcRRA3jPmk,mandiri,1000,-6.2097,106.90166,-6.218380,106.899969,ATM BTN,0
8,ATM CIMB Niaga,"SPBU Pertamina ATM Centre, Jalan Bekasi Timur ...",atm,ChIJiZsg1af0aS4Ro11lGyH9UcM,mandiri,1000,-6.2097,106.90166,-6.212319,106.900264,ATM CIMB Niaga,0
9,ATM CIMB Niaga,"Jl. Raya Bekasi No.KM 17, RT.7/RW.3, Jatinegar...",atm,ChIJVX_Xo7H0aS4R7zCX77Rv004,mandiri,1000,-6.2097,106.90166,-6.202227,106.904644,ATM CIMB Niaga,0
10,Mandiri ATM Alfamart Dermaga,"JL Dermaga Raya, No. 4 RT. 003 RW. 017, Klende...",atm,ChIJsyZPE1PzaS4RbWvoHjwXkN4,mandiri,1000,-6.2097,106.90166,-6.220890,106.910342,Mandiri ATM Alfamart Dermaga,0
11,Bank Mandiri Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No. 4, Rawamangun, Jati, Puloga...",bank,ChIJ-2eYub30aS4R_U7u5oQpTus,mandiri,1000,-6.2097,106.90166,-6.201320,106.890710,Bank Mandiri Jakarta Rawamangun Pegambiran,(021) 4892878
12,Atm Bank Dki,"Pasar Jaya Klender SS, Jl. Bekasi Timur Raya N...",atm,ChIJY7IpZ6j0aS4RMnCwUZJ42iE,mandiri,1000,-6.2097,106.90166,-6.212552,106.901747,Atm Bank Dki,0

In [12]:
datadummydrop=datadummy.drop(['customer_name_y'], axis = 1)
datadummydrop.columns = ['customer_name','customer_address','customer_type','place_id','keyword','radius','latitude_origin','longitude_origin','latitude_destination','longitude_destination','phone_number']
datadummydrop2=datadummydrop[['customer_name','customer_address','customer_type','keyword','radius', 'place_id','latitude_origin','longitude_origin','latitude_destination','longitude_destination','phone_number']]
datadummydrop2

,customer_name,customer_address,customer_type,keyword,radius,place_id,latitude_origin,longitude_origin,latitude_destination,longitude_destination,phone_number
0,ATM Mandiri,"Jl. Bekasi Timur Raya No.48c, RT.13/RW.2, Jati...",atm,mandiri,1000,ChIJU7kJa6_0aS4ReDXWEVlKU_U,-6.2097,106.90166,-6.208364,106.901700,0
1,Mandiri ATM Citra Klender,"Jl. I Gusti Ngurah Rai, RT.4/RW.6, Klender, Ko...",bank,mandiri,1000,ChIJZdR0VVXzaS4RtsxK_SQ_5WA,-6.2097,106.90166,-6.213986,106.903752,(021) 86612125
2,Mandiri ATM MITSUBISHI Pulo Gadung,"Jl. Raya Bekasi Pulogadung, RT.2/RW.14, Cipina...",bank,mandiri,1000,ChIJZ04RRKH0aS4R_intKrJbNXM,-6.2097,106.90166,-6.210821,106.893506,(021) 52997777
3,ATM Mandiri,"Toserba Berkah, Jl. Gurame No.31, RT.4/RW.6, J...",atm,mandiri,1000,ChIJq3xR3bv0aS4RxuJJ79yN3AE,-6.2097,106.90166,-6.200196,106.896083,0
4,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,"Jalan Pahlawan Revolusi No.12 RT.9/RW.4, RT.11...",bank,mandiri,1000,ChIJyUcV9lnzaS4R5feGiOKucYk,-6.2097,106.90166,-6.217153,106.899841,(021) 8625120
5,Mandiri Micro Business Unit Jakarta Mall Klender,Komplek Ruko Blok B1 No.6 Jl. I Gusti Ngurah R...,bank,mandiri,1000,ChIJ-frTp6r0aS4ROzw41QWz3WE,-6.2097,106.90166,-6.213992,106.903753,(021) 86612125
6,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No.5a, RT.12/RW.7, Rawamangun, ...",atm,mandiri,1000,ChIJ6Ugu3L30aS4RNE-0s3lxyXg,-6.2097,106.90166,-6.200591,106.890660,(021) 52997777
7,ATM BTN,"Jl. Pahlawan Revolusi, RT.11/RW.5, Klender, Ko...",atm,mandiri,1000,ChIJG3jbLVjzaS4RzCcRRA3jPmk,-6.2097,106.90166,-6.218380,106.899969,0
8,ATM CIMB Niaga,"SPBU Pertamina ATM Centre, Jalan Bekasi Timur ...",atm,mandiri,1000,ChIJiZsg1af0aS4Ro11lGyH9UcM,-6.2097,106.90166,-6.212319,106.900264,0
9,ATM CIMB Niaga,"Jl. Raya Bekasi No.KM 17, RT.7/RW.3, Jatinegar...",atm,mandiri,1000,ChIJVX_Xo7H0aS4R7zCX77Rv004,-6.2097,106.90166,-6.202227,106.904644,0
10,Mandiri ATM Alfamart Dermaga,"JL Dermaga Raya, No. 4 RT. 003 RW. 017, Klende...",atm,mandiri,1000,ChIJsyZPE1PzaS4RbWvoHjwXkN4,-6.2097,106.90166,-6.220890,106.910342,0
11,Bank Mandiri Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No. 4, Rawamangun, Jati, Puloga...",bank,mandiri,1000,ChIJ-2eYub30aS4R_U7u5oQpTus,-6.2097,106.90166,-6.201320,106.890710,(021) 4892878
12,Atm Bank Dki,"Pasar Jaya Klender SS, Jl. Bekasi Timur Raya N...",atm,mandiri,1000,ChIJY7IpZ6j0aS4RMnCwUZJ42iE,-6.2097,106.90166,-6.212552,106.901747,0

# distance matrix

In [13]:
import pandas as pd
import googlemaps

In [14]:
API_key = 'AIzaSyCi3bprtv8GbZUNpU4rE2eQ8oguxfDkRjg'#enter Google Maps API key
gmaps = googlemaps.Client(key=API_key)

In [15]:
distancedrive,distancewalks = [],[]

# Loop through each row in the data frame using pairwise
for number in range(datadummydrop2.shape[0]):
      #Assign latitude and longitude as origin/departure points
    LatOrigin = datadummydrop2['latitude_origin'][number]
    LongOrigin = datadummydrop2['longitude_origin'][number]
    origins = (LatOrigin,LongOrigin)

      #Assign latitude and longitude from the next row as the destination point
    LatDest = datadummydrop2['latitude_destination'][number]  # Save value as lat
    LongDest = datadummydrop2['longitude_destination'][number] # Save value as lat
    destination = (LatDest,LongDest)

      #pass origin and destination variables to distance_matrix function# output in meters
    result = gmaps.distance_matrix(origins, destination, mode='driving',avoid='tolls',units='metric',departure_time=1703981100)["rows"][0]["elements"][0]["distance"]["value"]
    result1 = gmaps.distance_matrix(origins, destination, mode='walking',avoid='tolls',units='metric',departure_time=1703981100)["rows"][0]["elements"][0]["distance"]["value"]
 #1703981100    #1606867500 
      #append result to list
    distancedrive.append(result)
    distancewalks.append(result1)

In [16]:
datadummydrop2['Distance_to_Infra_driving']=distancedrive
datadummydrop2['Distance_to_Infra_walking']=distancewalks
datadummydrop3=datadummydrop2.sort_values(by=['Distance_to_Infra_driving'],ascending=True,ignore_index=True)
datadummydrop3

C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
C:\Users\ASUS\anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,customer_name,customer_address,customer_type,keyword,radius,place_id,latitude_origin,longitude_origin,latitude_destination,longitude_destination,phone_number,Distance_to_Infra_driving,Distance_to_Infra_walking
0,Atm Bank Dki,"Pasar Jaya Klender SS, Jl. Bekasi Timur Raya N...",atm,mandiri,1000,ChIJY7IpZ6j0aS4RMnCwUZJ42iE,-6.2097,106.90166,-6.212552,106.901747,0,365,369
1,Bank Mandiri - Branch Jakarta Pahlawan Revolusi,"Jalan Pahlawan Revolusi No.12 RT.9/RW.4, RT.11...",bank,mandiri,1000,ChIJyUcV9lnzaS4R5feGiOKucYk,-6.2097,106.90166,-6.217153,106.899841,(021) 8625120,853,907
2,ATM BTN,"Jl. Pahlawan Revolusi, RT.11/RW.5, Klender, Ko...",atm,mandiri,1000,ChIJG3jbLVjzaS4RzCcRRA3jPmk,-6.2097,106.90166,-6.218380,106.899969,0,985,1039
3,Mandiri ATM MITSUBISHI Pulo Gadung,"Jl. Raya Bekasi Pulogadung, RT.2/RW.14, Cipina...",bank,mandiri,1000,ChIJZ04RRKH0aS4R_intKrJbNXM,-6.2097,106.90166,-6.210821,106.893506,(021) 52997777,1366,1339
4,ATM CIMB Niaga,"SPBU Pertamina ATM Centre, Jalan Bekasi Timur ...",atm,mandiri,1000,ChIJiZsg1af0aS4Ro11lGyH9UcM,-6.2097,106.90166,-6.212319,106.900264,0,1560,513
5,ATM Mandiri,"Jl. Bekasi Timur Raya No.48c, RT.13/RW.2, Jati...",atm,mandiri,1000,ChIJU7kJa6_0aS4ReDXWEVlKU_U,-6.2097,106.90166,-6.208364,106.901700,0,1801,209
6,Mandiri ATM Citra Klender,"Jl. I Gusti Ngurah Rai, RT.4/RW.6, Klender, Ko...",bank,mandiri,1000,ChIJZdR0VVXzaS4RtsxK_SQ_5WA,-6.2097,106.90166,-6.213986,106.903752,(021) 86612125,2091,1587
7,Mandiri Micro Business Unit Jakarta Mall Klender,Komplek Ruko Blok B1 No.6 Jl. I Gusti Ngurah R...,bank,mandiri,1000,ChIJ-frTp6r0aS4ROzw41QWz3WE,-6.2097,106.90166,-6.213992,106.903753,(021) 86612125,2091,1587
8,Mandiri ATM Alfamart Dermaga,"JL Dermaga Raya, No. 4 RT. 003 RW. 017, Klende...",atm,mandiri,1000,ChIJsyZPE1PzaS4RbWvoHjwXkN4,-6.2097,106.90166,-6.220890,106.910342,0,2291,2344
9,Mandiri ATM KCP Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No.5a, RT.12/RW.7, Rawamangun, ...",atm,mandiri,1000,ChIJ6Ugu3L30aS4RNE-0s3lxyXg,-6.2097,106.90166,-6.200591,106.890660,(021) 52997777,2988,2583
10,Bank Mandiri Jakarta Rawamangun Pegambiran,"Jl. Pegambiran No. 4, Rawamangun, Jati, Puloga...",bank,mandiri,1000,ChIJ-2eYub30aS4R_U7u5oQpTus,-6.2097,106.90166,-6.201320,106.890710,(021) 4892878,3064,2506
11,ATM Mandiri,"Toserba Berkah, Jl. Gurame No.31, RT.4/RW.6, J...",atm,mandiri,1000,ChIJq3xR3bv0aS4RxuJJ79yN3AE,-6.2097,106.90166,-6.200196,106.896083,0,3637,2046
12,ATM CIMB Niaga,"Jl. Raya Bekasi No.KM 17, RT.7/RW.3, Jatinegar...",atm,mandiri,1000,ChIJVX_Xo7H0aS4R7zCX77Rv004,-6.2097,106.90166,-6.202227,106.904644,0,4576,973

In [17]:
datadummydrop3.to_csv('distance_auto.csv',index=False)

In [31]:
import csv
import psycopg2

csv_data = csv.reader(open('distance_auto.csv'))

database = psycopg2.connect (database = "customerDB", 
                             user="postgres", 
                             password="postgres", 
                             host="localhost")

cursor = database.cursor()


cursor.execute("""Create Table test
              (customer_name varchar(150),
              customer_address varchar(300),
              customer_type varchar(100),
              keyword varchar (50),
              radius varchar(10),
              place_id varchar(300),
              latittude_origin varchar(30),
              longitude_origin varchar(30),
              latittude_destination varchar(30),
              longitude_destination varchar(30),
              phone_number varchar(15),
              Distance_to_Infra_driving varchar(15),
              Distance_to_Infra_walking varchar(15));""")

print ("Table created successfully") 

next(csv_data)
for row in csv_data:

    cursor.execute("""Insert into test (customer_name, customer_address, customer_type, keyword, radius, place_id, latittude_origin, longitude_origin, latittude_destination, longitude_destination, phone_number, Distance_to_Infra_driving, Distance_to_Infra_walking) VALUES (%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)""", row)

cursor.close()
    
database.commit()
database.close()

print ("CSV imported")

Table created successfully
CSV imported